languageCode = 'en-us'
title = 'DIY Web Dev'

[markup]
        [markup.highlight]
                style = 'catppuccin-latte'

[menus]
        [[menus.main]]
                name = 'Course'
                pageRef = '/courses/web-dev/'
        [[menus.main]]
                name = 'Projects'
                pageRef = '/projects/'
        [[menus.main]]
                name = 'Blog'
                pageRef = '/blog/'
        [[menus.main]]
                name = 'Resume'
                pageRef = '/resume/'

[build]
        [build.buildStats]
                enable = true
        [[build.cachebusters]]
                source = 'assets/notwatching/hugo_stats\.json'
                target = 'css'
        [[build.cachebusters]]
                source = '(postcss|tailwind)\.config\.js'
                target = 'css'

[module]
        [[module.mounts]]
                source = 'assets'
                target = 'assets'
        [[module.mounts]]
                disableWatch = true
                source = 'hugo_stats.json'
                target = 'assets/notwatching/hugo_stats.json'
